backend:
  name: github
  repo: zhambaleilo/Stepik-leadership-course
  branch: main

site_url: https://my-pro-skills.ru/
display_url: https://my-pro-skills.ru/

media_folder: "articles/img"
public_folder: "/articles/img"

collections:
  - name: "articles"
    label: "Статьи"
    folder: "articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Краткое описание для карточки (одна строка)", name: "description", widget: "string"}
      - {label: "Подзаголовок статьи (можно длинный, не обяз.)", name: "lead", widget: "text", required: false}      
      - {label: "Теги через запятую", name: "tags", widget: "string", required: false}
      - {label: "Обложка (необязательно)", name: "cover", widget: "image", required: false}
      - {label: "Текст статьи", name: "body", widget: "markdown"}
